### ISSUE TITLE
tokenization breaks sometimes with 2.2.2

### ISSUE THREAD

**Issue by akosyakov** [NeekSandhu/onigasm#17] opened 2019-05-29 09:02 UTC
caused by this commit: https://github.com/NeekSandhu/onigasm/commit/65fd5b5b1a2475cc9c57e1c9a2e8b45f09d424f4

Originally reported in Theia for PHP grammar: https://github.com/theia-ide/theia/issues/4966

**Comment by mofux** [comment] 2019-05-29 09:57
I think I can shed some light on this issue. I have been seeing this problem even with previous versions of onigasm, but always limited to the `php` grammar (@akosyakov does it fail for you with other grammars too?). 

In my case, whenever a built-in PHP function like `empty` was tokenized, the tokenizer would fail. Diving deeper into the issue, the `createOnigScanner` function that is passed when initializing the registry gets called with an array `[undefined]` when it encounters a php built-in function. Passing that array to the OnigScanner would make it fail. Below you can see the code I've used to work around the issue (surprisingly, it doesn't break highlighting at all):

```javascript
createOnigScanner: (sources) => {
	
	// FIXME: 
	// with php "$var = empty()" sources would be [undefined] which will crash,
	// therefore we sanitize the sources array here. Pretty sure there must be a
	// root cause for this problem, still to find yet
	if (sources[0] === undefined) sources.length = 0;
	return new oniglib.OnigScanner(sources);
	
},
```

**Comment by akosyakov** [comment] 2019-05-29 10:51
No, i have not seen it with other grammars. Do you have an example of php files which breaks with 2.2.1? Just want to try it.

**Comment by mofux** [comment] 2019-05-29 11:41
I cannot reproduce this issue I described above with `2.2.1`, maybe it was fixed in the meantime. However, I'm getting the same error as you when using `2.2.2` on php files (even empty ones). Not sure what's going on.

**Comment by NeekSandhu** [comment] 2019-05-31 06:01
I read the thread over at Theia issues, and while I do understand the problem, I'd highly appreciate if you guys can give me a filtered and definitive summary of all the observations you guys have made till now.

Because I'm bit confused. @akosyakov mentions how `2.2.1` works fine while @mofux says how problems have been around even in the previous versions?

**Comment by akosyakov** [comment] 2019-06-01 05:08
@NeekSandhu i believe it only affects 2.2.2 and in 2.2.1 it used to work fine

**Comment by NeekSandhu** [comment] 2019-06-01 07:20
Can you please share the grammar file along with the text that's being tokenized (the one that causes the error). Thanks!

**Comment by akosyakov** [comment] 2019-06-01 08:37
grammar is here: https://github.com/theia-ide/theia/blob/master/packages/textmate-grammars/data/php.tmLanguage.json

code snippet:
```php
<?php
  // Declare the variable 'string' and assign it a value.
  // The <br> is the HTML equivalent to a new line.
  $string = 'Hello World!<br>';

  // You can echo the variable, similar to the way you would echo a string.
  echo $string;

  // You could also use print.
  print $string;

  // Or, if you are familiar with C, printf can be used too.
  printf('%s', $string);
?>
```

**Comment by aeschli** [comment] 2019-11-13 16:29
Please try onigasm@2.2.4 with the fix for the issue.

**Closed by aeschli** 2019-11-13 16:29 UTC
